#!/bin/bash
# Lista todos los presets disponibles

echo "=========================================================================="
echo "                   VISUAL ENGINE - PRESETS DISPONIBLES"
echo "=========================================================================="
echo ""
echo "═══════════════════════ CATEGORY 1: CPU RENDERING ══════════════════════"
echo ""
echo "  1. Minimal Generative (default)"
echo "     Comando: ./run.sh 1"
echo "     Una forma generativa central minimal | CPU (Pygame)"
echo ""
echo "═══════════════════════ CATEGORY 2: FRACTALS/SDF ═══════════════════════"
echo ""
echo "  2. VFX Shader Engine"
echo "     Comando: ./run.sh 2"
echo "     Raymarching 3D con SDF, FBM, morfing de formas | GPU"
echo ""
echo "  3. Menger Sponge"
echo "     Comando: ./run.sh 3"
echo "     Fractal cúbico 3D con evolución de iteraciones | GPU"
echo ""
echo "  4. Mandelbulb"
echo "     Comando: ./run.sh 4"
echo "     Fractal 3D orgánico con power evolutivo | GPU"
echo ""
echo "  5. Apollonian Gasket"
echo "     Comando: ./run.sh 5"
echo "     Empaquetamiento infinito de círculos | GPU"
echo ""
echo "  6. Sierpinski Pyramid"
echo "     Comando: ./run.sh 6"
echo "     Fractal tetraédrico con folding 3D | GPU"
echo ""
echo " 23. Fractal Morphing"
echo "     Comando: ./run.sh 23"
echo "     5 metamorfosis evolutivas por bassline | GPU + MIDI"
echo ""
echo " 24. Fractal Tunnel"
echo "     Comando: ./run.sh 24"
echo "     Viaje infinito con box flotante reactivo | GPU + MIDI"
echo ""
echo "════════════════════ CATEGORY 3: PARTICLE/FLOW FIELD ═══════════════════"
echo ""
echo "  7. Curl Noise Flow"
echo "     Comando: ./run.sh 7"
echo "     Campo de flujo divergence-free orgánico | GPU"
echo ""
echo "  8. Magnetic Field Lines"
echo "     Comando: ./run.sh 8"
echo "     Visualización de campo magnético multi-carga | GPU"
echo ""
echo "  9. Swarm Intelligence"
echo "     Comando: ./run.sh 9"
echo "     Comportamiento emergente de enjambre (boids) | GPU"
echo ""
echo " 10. Turbulence Field"
echo "     Comando: ./run.sh 10"
echo "     Movimiento caótico de partículas en turbulencia | GPU"
echo ""
echo "════════════════════════ CATEGORY 4: GLITCH/FEEDBACK ═══════════════════"
echo ""
echo " 11. Pixel Sorting"
echo "     Comando: ./run.sh 11"
echo "     Ordenamiento de píxeles vertical/horizontal | GPU"
echo ""
echo " 12. Datamosh Feedback"
echo "     Comando: ./run.sh 12"
echo "     Loops de feedback con motion vectors | GPU"
echo ""
echo " 13. RGB Displacement"
echo "     Comando: ./run.sh 13"
echo "     Separación cromática angular dinámica | GPU"
echo ""
echo " 14. Scanline Corruption"
echo "     Comando: ./run.sh 14"
echo "     Glitches tipo CRT con scanlines | GPU"
echo ""
echo "══════════════════ CATEGORY 5: GENERATIVE PATTERNS ═════════════════════"
echo ""
echo " 15. Voronoi Cells"
echo "     Comando: ./run.sh 15"
echo "     División celular orgánica animada | GPU"
echo ""
echo " 16. Reaction-Diffusion"
echo "     Comando: ./run.sh 16"
echo "     Modelo Gray-Scott simplificado | GPU"
echo ""
echo " 17. Wave Interference"
echo "     Comando: ./run.sh 17"
echo "     Interferencia de múltiples fuentes de ondas | GPU"
echo ""
echo " 18. Truchet Tiles"
echo "     Comando: ./run.sh 18"
echo "     Patrón procedural evolutivo | GPU"
echo ""
echo "═══════════════════ CATEGORY 6: HYBRID/EXPERIMENTAL ════════════════════"
echo ""
echo " 19. Quantum Foam"
echo "     Comando: ./run.sh 19"
echo "     Campo visual probabilístico con colapso | GPU"
echo ""
echo " 20. Liquid Metal"
echo "     Comando: ./run.sh 20"
echo "     Metaballs morfing líquido | GPU"
echo ""
echo " 21. Crystal Growth"
echo "     Comando: ./run.sh 21"
echo "     Autómata celular con crecimiento cristalino | GPU"
echo ""
 echo " 22. Neural Noise"
echo "     Comando: ./run.sh 22"
echo "     Ruido multi-octava con domain warping | GPU"
echo ""
echo "════════════════════ CATEGORY 7: AUDIO REACTIVE ════════════════════════"
echo ""
 echo " 25. Oscilloscope Glitch"
echo "     Comando: ./run.sh 25"
echo "     Visualizador de onda real (Scarlett) + Glitch | GPU + Audio"
echo ""
 echo " 26. Ethereal Particle Organism"
echo "     Comando: ./run.sh 26"
echo "     Partículas orgánicas que nacen con el sonido | Drone | GPU + Audio"
echo ""
 echo " 27. Radial Frequency Scope"
echo "     Comando: ./run.sh 27"
echo "     Anillo de frecuencias radial con líneas orbitales | Shadertoy Port | GPU + Audio"
echo ""
echo " 28. Neon Kinetic Mandala"
echo "     Comando: ./run.sh 28"
echo "     Mandala hexagonal caleidoscópico con haces de luz | GPU + Audio"
echo ""
echo " 29. Lissajous Light Painting"
echo "     Comando: ./run.sh 29"
echo "     Curvas armónicas con estela de luz (Feedback) | GPU + Audio"
echo ""
echo " 30. Cosmic Swirl VFX"
echo "     Comando: ./run.sh 30"
echo "     Remolino cósmico reactivo | GPU + Audio"
echo ""
echo " 31. Triple Oscilloscope"
echo "     Comando: ./run.sh 31"
echo "     Osciloscopio triple con interferencia | GPU + Audio"
echo ""
echo " 32. Geometric Minimalism"
echo "     Comando: ./run.sh 32"
echo "     Círculos y líneas pulsantes minimalistas | GPU + Audio"
echo ""
echo " 33. Organic Fluid"
echo "     Comando: ./run.sh 33"
echo "     Fluidos metaball tipo tinta en agua | GPU + Audio"
echo ""
echo " 34. Atmospheric Particles"
echo "     Comando: ./run.sh 34"
echo "     Partículas de polvo cósmico y flow fields | GPU + Audio"
echo ""
echo " 35. Synthwave Retro"
echo "     Comando: ./run.sh 35"
echo "     Paisaje retro 80s con sol y rejilla neón | GPU + Audio"
echo ""
echo " 36. Mandelbrot Glitch 3D"
echo "     Comando: ./run.sh 36"
echo "     Mandelbulb 3D inmersivo con colores y glitch reactivos | GPU + Audio + MIDI"
echo ""
echo " 37. Desert Swarm"
echo "     Comando: ./run.sh 37"
echo "     Partículas de arena orgánicas y rayos de sol | Volumétrico | GPU + Audio"
echo ""
echo "=========================================================================="
echo "MIDI MAPPING (todos los presets):"
echo "  🥁 Kick (60)       → Pulsa/expande forma, aumenta complejidad"
echo "  🎩 Hats (62)       → Glitch/distorsión espacial"
echo "  🔔 Tom 1 (64)      → Modula geometría/escala"
echo "  🔔 Tom 2 (65)      → Modula rotación/movimiento"
echo ""
echo "MIDI MAPPING AVANZADO (presets 23-24):"
echo "  🎸 Bassline (Ch1)  → Metamorfosis evolutiva / Control de velocidad"
echo "=========================================================================="
echo ""
echo "💡 Tip: Todos los presets son evolutivos - la forma cambia en cada kick"
echo "📐 Formato: Instagram Reels (1080x1920 - Vertical 9:16)"
echo "🎨 Estilo: Minimal, Monochrome, Glow, Generative"
echo ""
